version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/__pycache__
    environment:
      - PYTHONPATH=/app
      - FLASK_ENV=development
    command: python -m flask run --host=0.0.0.0 --port=8000

  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/app
      - /app/__pycache__
    environment:
      - PYTHONPATH=/app
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root --no-browser --allow-root

  tests:
    build: .
    volumes:
      - .:/app
      - /app/__pycache__
    environment:
      - PYTHONPATH=/app
    command: pytest tests/ -v --cov=src